[ADD] Condiciones para ser Media Partners
phpmx/comunidad pull request #22
Opened 2022-09-26 23:17 UTC by marianorenteria

Propongo la versión 1 de los lineamientos que podríamos considerar para ser media partners de eventos de otras organizaciones.

2022-09-27 00:07 UTC, eisenheimjelid requested changes
Yo creo que podemos incluir de 1 y hasta 5 publicaciones en las principales redes sociales de la comunidad (Twitter, Facebook, e Instragram), porque igual depende del tiempo para llevar a cabo el evento. Es decir, no es lo mismo hacer 2 publicaciones en 2 semanas, que en 6 meses; así que un máximo de 5 publicaciones, dependiendo del tiempo de antelación del evento es más razonable.

2022-09-27 00:07 UTC, eisenheimjelid commented on media-partner
> +La comunidad de PHP México gusta de colaborar y hacer sinergia con comunidades u organizaciones, algo común que nos solicitan es ser Media Partners, lo cual normalmente consiste en incluir nuestro lo
```suggestion
La comunidad de PHP México gusta de colaborar y hacer sinergia con comunidades u organizaciones, algo común que nos solicitan es ser Media Partners, lo cual normalmente consiste en incluir nuestro logo en la publicidad del evento a cambio de que nosotros promocionemos el evento con nuestra comunidad.
```

2022-09-27 00:07 UTC, eisenheimjelid commented on media-partner
> +En caso de desar más publicidad en nuestras redes sociales, empresas pueden adquirir alguno de nuestros paquetes de patrocinios.
```suggestion
En caso de desear más publicidad en nuestras redes sociales, las empresas pueden adquirir alguno de nuestros paquetes de patrocinios.
```

2022-09-27 00:07 UTC, eisenheimjelid commented on media-partner
> +Si tu organización o comunidad desea que PHP México participe como Media Partner, deberás consierar los siguientes lineamientos:
```suggestion
Si tu organización o comunidad desea que PHP México participe como Media Partner, deberás considerar los siguientes lineamientos: 
```

2022-09-27 00:07 UTC, eisenheimjelid commented on media-partner
> +5. El evento impulsa el uso de tecnologias web en México
```suggestion
5. El evento impulsa el uso de tecnologías web en México
```

2022-10-22 02:20 UTC, jashk approved these changes

2022-10-22 12:31 UTC, marianorenteria commented
@jashk @eisenheimjelid le hice unos cambios, yo creo con eso ya le damos fuego 🔥 no?

2022-10-22 13:13 UTC, eisenheimjelid approved these changes

2022-10-22 14:55 UTC, merged